POST http://localhost:8000/products
Content-Type: application/json

{
	"name": "Product Test",
	"price": 13.45
}

###

GET http://localhost:8000/products/
Content-Type: application/json

###

GET http://localhost:8000/products/68b21ade-382b-42a1-94c4-78331392b0e9
Content-Type: application/json

###

PUT http://localhost:8000/products/68b21ade-382b-42a1-94c4-78331392b0e9
Content-Type: application/json

{
	"name": "Product Updated",
	"price": 198.40
}

###

DELETE http://localhost:8000/products/68b21ade-382b-42a1-94c4-78331392b0e9
Content-Type: application/json

###